### PR TITLE
TE-7001 Updated Symfony console commands to always return int.

### PR DESCRIPTION
**Pull request by stereomon**
- Developer(s): @stereomon

- Ticket: https://spryker.atlassian.net/browse/TE-7001

- Academy PR: ACADEMY_URL_HERE

- Release Group: https://release.spryker.com/release-groups/view/2897

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   EventBehavior         | minor                 |                       |

-----------------------------------------

##### Change log

Improvements

- Always return `int` for console command.

### CODE REVIEW

**Comment by dereuromark** [comment]
This should be a minor as changing signature is always at least internal BC break.

**Comment by dereuromark** [comment]
But then again: You dont use a constraint update here, you use a normal allowing release, right?

**Comment by dereuromark** [comment]
Might need https://github.com/spryker/event-behavior/pull/51 to be included for full travis green.

**Review by a-sabaa — APPROVED** [review]

**Comment by dereuromark** [comment]
This introduced a bug, see https://spryker.atlassian.net/browse/TE-7780
3 people didnt spot this. PHPStan ( https://github.com/spryker/event-behavior/pull/51 ) would have.

We need to start using proper protocols for code quality also for standalone modules.

**Pull request merged**
