### PR TITLE
CORE 4129 make travis run tests with mysql

### PR DESCRIPTION
**Pull request by stereomon**
- Developer(s): @stereomon

- Peer Reviewer:

- Ticket: https://spryker.atlassian.net/browse/CORE-4129

- Academy PR: ACADEMY_URL_HERE

- Release Group: https://release.spryker.com/release-groups/view/54

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department
- [ ] All new or heavily changed classes get an "A" rating (Scrutinizer), except Facades, Factories, QueryContainers and Tests

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   EventBehavior         | patch (currently 0.x)  |                       |

#### Release Notes

Added missing identifierQuoting attribute to schema file to prevent errors when running with MySql.

-----------------------------------------

#### Module EventBehavior

_**Patch:** Backwards-compatible bug fix_

Def of done (by responsible developer):
- [ ] All changes are backward-compatible. Outdated code is marked as deprecated.
- [ ] The change is isolated and not mixed with any cleanups or other changes.
- [ ] New code fits to the architecture rules.
- [ ] All new or changed business logic is covered by functional tests (in Zed business layer).

##### Change log

Bugfixes

- Added missing identifierQuoting to schema definition.
- Updated VARCHAR to LONGVARCHAR.

### CODE REVIEW

**Comment by dereuromark** [comment]
@PhilinTv Is this still releasable?

**Comment by dereuromark** [comment]
@ehsanmx What do you think?

**Comment by dereuromark** [comment]
How does this relate to https://github.com/spryker/event-behavior/pull/12?

**Comment by dereuromark** [comment]
A db change like this has to be a minor.
Also, could this be merged into the other ticket then? So we release this together? Does that make sense?

**Comment by gechetspr** [comment]
Going to be fixed in https://github.com/spryker/event-behavior/pull/15

**Pull request closed without merging**
