### PR TITLE
FRW-332 Change min PHP version to 8.0

### PR DESCRIPTION
**Pull request by geega**
Ticket: https://spryker.atlassian.net/browse/FRW-332

### CODE REVIEW

**Comment by geega** [comment]
Looks like some CI errors are not PR related

**Comment by dereuromark** [comment]
You can also fix them first on master and then rebase.

**Review by dimitriyTsemma — APPROVED** [review]

**Comment by michbeck** [comment]
> Class \"Orm\\Zed\\EventBehavior\\Persistence\\Base\\SpyEventBehaviorEntityChange\" not found

Currently your boostrap file spl_autoload_register only checks for transfers. As soon as you have other classes you need to updated this, e.g. like this:
 
https://github.com/spryker-eco/unzer-api/blob/master/tests/bootstrap.php#L31-L52

Idk, where you copied the file, but within related [standalone module testing documentation](https://spryker.atlassian.net/wiki/spaces/CORE/pages/2868248862/Standalone+module+testing#Bootstrapping) you can find exactly this as an example in bootstrapping part too.

**Comment by michbeck** [comment]
Don't forget to update composer. Currently CI is green but test still fail. At all, if there are problems integrating the standalone testing please take a look the [FAQ section](https://spryker.atlassian.net/wiki/spaces/CORE/pages/2868248862/Standalone+module+testing#FAQ). If there is no answer feel free to contact me.

**Comment by dereuromark** [comment]
Can we fix CI here? Otherwise looks good

**Comment by geega** [comment]
@dereuromark  I fixed some issues related with dependencies but now have issues with connection to database. But not understand why? Could you help me?

**Comment by dereuromark** [comment]
I recommend adding a follow up ticket to fix prefer lowest
For now we dont have time and should skip (I adjusted CI file)

**Comment by dereuromark** [comment]
> [Propel\Runtime\Exception\RuntimeException] No connection defined for database "zed". Did you forget to define a connection or is it wrong written? 

I dont think it is fixed just yet, the tests are just | true skipped for now.

**Comment by geega** [comment]
I don't touch tests because tests need deep refactoring, only phpstan validation for prefer-lowest.

**Comment by dereuromark** [comment]
Then lets make follow up ticket to fix tests as suggested

**Comment by asmarovydlo** [comment]
> Then lets make follow up ticket to fix tests as suggested

Follow-up ticket https://spryker.atlassian.net/browse/FRW-501

**Pull request merged**
